### ISSUE TITLE
Hooking code is a bit rubbish

### ISSUE THREAD

**Issue by MrSapps** [rcxrdx/WitcherHooked#1]
This is much better:

https://github.com/AliveTeam/alive_reversing/blob/master/Source/AliveLib/ExportHooker.cpp

It hooks any function exported from the dll using the address that is in the name of the function.

E.g:

void blah_deadbeef() would hook 0xdeadbeef and redirect to blah_deadbeef func. Using the NOT_IMPLEMENTED() macro does the reverse so that calling blah_deadbeef() jumps to 0xdeadbeef.

A lot better the the old code you have here ;)

**Comment by rcxrdx** [comment]
Ahahah, rubbish seems a bit harsh, I think this old hooking code was small, simple and did the work :D

But the features on the new one seem very nice, even if it adds a dependency, I am definitely going to try it, thanks.

By the way, I saw the amazing progress you have done on Abe's Exoddus, congrats!

**Comment by MrSapps** [comment]
Cheers - if you decided to use the new code and need a hand setting it up let me know :)
